#!/usr/bin/env python3

import os
import time
import requests
from datetime import datetime
from dotenv import load_dotenv
from jira import JIRA

load_dotenv()

class JiraAlertIntegration:
    def __init__(self):
        self.jira_server = os.getenv("JIRA_SERVER")
        self.jira_email = os.getenv("JIRA_EMAIL")
        self.jira_token = os.getenv("JIRA_API_TOKEN")
        self.project_key = os.getenv("JIRA_PROJECT_KEY")
        self.prometheus_url = os.getenv("PROMETHEUS_URL")
        self.processed_alerts = set()

        self.jira = JIRA(
            options={"server": self.jira_server},
            basic_auth=(self.jira_email, self.jira_token)
        )

        print("Connected to Jira successfully.")

    def get_alerts(self):
        url = f"{self.prometheus_url}/api/v1/alerts"
        response = requests.get(url, timeout=10)

        if response.status_code == 200:
            return response.json().get("data", {}).get("alerts", [])

        print("Failed to fetch Prometheus alerts:", response.status_code)
        return []

    def create_ticket(self, alert):
        labels = alert.get("labels", {})
        annotations = alert.get("annotations", {})

        alert_name = labels.get("alertname", "Unknown Alert")
        severity = labels.get("severity", "unknown")
        service = labels.get("service", "general")

        summary = f"[ALERT] {annotations.get('summary', alert_name)}"

        description = f"""
Alert Name: {alert_name}
Severity: {severity}
Service: {service}
Instance: {labels.get('instance', 'unknown')}
State: {alert.get('state', 'unknown')}
Active Since: {alert.get('activeAt', 'unknown')}

Description:
{annotations.get('description', 'No description available')}

Generated By: SysOps Monitoring System
Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
"""

        priority = "High" if severity == "critical" else "Medium"

        issue = self.jira.create_issue(fields={
            "project": {"key": self.project_key},
            "summary": summary,
            "description": description,
            "issuetype": {"name": "Task"},
            "priority": {"name": priority},
            "labels": ["monitoring", f"severity-{severity}", f"service-{service}"]
        })

        print(f"Jira ticket created: {issue.key}")
        return issue.key

    def process_alerts(self):
        alerts = self.get_alerts()

        if not alerts:
            print("No active alerts found.")
            return

        for alert in alerts:
            labels = alert.get("labels", {})
            alert_id = f"{labels.get('alertname')}-{labels.get('instance')}"

            if alert.get("state") == "firing" and alert_id not in self.processed_alerts:
                print("Processing alert:", alert_id)
                self.create_ticket(alert)
                self.processed_alerts.add(alert_id)

    def run(self):
        print("Starting monitoring loop. Press CTRL+C to stop.")

        while True:
            self.process_alerts()
            time.sleep(30)

if __name__ == "__main__":
    app = JiraAlertIntegration()
    app.run()
